#!/usr/bin/env python3
"""
Copy Maximo attachments using a manifest generated by build_attachment_manifest.py.

Default mode is dry-run. Add --execute to actually copy files.
"""

from __future__ import annotations

import argparse
import csv
import shutil
from pathlib import Path


def same_size(source: Path, dest: Path) -> bool:
    return source.exists() and dest.exists() and source.stat().st_size == dest.stat().st_size


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True, help="Manifest CSV")
    parser.add_argument("--log", required=True, help="Copy result log CSV")
    parser.add_argument("--execute", action="store_true", help="Actually copy files")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite destination files")
    args = parser.parse_args()

    totals = {
        "rows": 0,
        "copied": 0,
        "dry_run_ready": 0,
        "missing_source": 0,
        "skipped_existing_same_size": 0,
        "skipped_existing_different_size": 0,
        "errors": 0,
    }

    with Path(args.manifest).open(newline="", encoding="utf-8") as src, Path(args.log).open(
        "w", newline="", encoding="utf-8"
    ) as log_file:
        reader = csv.DictReader(src)
        fieldnames = list(reader.fieldnames or []) + ["copy_action", "copy_error"]
        writer = csv.DictWriter(log_file, fieldnames=fieldnames)
        writer.writeheader()

        for row in reader:
            totals["rows"] += 1
            source = Path(row["source_path"])
            dest = Path(row["dest_path"])
            action = ""
            error = ""

            try:
                if not source.exists():
                    action = "missing_source"
                    totals["missing_source"] += 1
                elif dest.exists() and same_size(source, dest) and not args.overwrite:
                    action = "skipped_existing_same_size"
                    totals["skipped_existing_same_size"] += 1
                elif dest.exists() and not args.overwrite:
                    action = "skipped_existing_different_size"
                    totals["skipped_existing_different_size"] += 1
                elif not args.execute:
                    action = "dry_run_ready"
                    totals["dry_run_ready"] += 1
                else:
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(source, dest)
                    action = "copied"
                    totals["copied"] += 1
            except Exception as exc:  # Keep going so one bad file does not stop the run.
                action = "error"
                error = str(exc)
                totals["errors"] += 1

            row["copy_action"] = action
            row["copy_error"] = error
            writer.writerow(row)

    mode = "EXECUTE" if args.execute else "DRY RUN"
    print("Mode:", mode)
    print("Log written:", args.log)
    for key, value in totals.items():
        print(f"{key}: {value}")
    return 1 if totals["errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
